name: number_trivia
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts:
  # Service locator
  get_it: 
  # Bloc for state management
  flutter_bloc: 
  bloc: 
  # Value equality
  equatable: 
  # Functional programming thingies
  dartz: 
  # Remote API
  dio:
  retrofit:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  retrofit_generator:
  mocktail:

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
