name: ble_connection
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.33.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.11
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
